{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 10,
  "build_id": "v0.107.1",
  "game_mode": "daily",
  "killed_by_encounter": "ENCOUNTER.THE_INSATIABLE_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.TACTICIAN"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STRANGLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLANKING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STRANGLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BACKSTAB"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.BACKSTAB"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.BACKSTAB"
              },
              {
                "id": "CARD.FOOTWORK"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FOOTWORK"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FOOTWORK"
              },
              {
                "id": "CARD.DEADLY_POISON"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEADLY_POISON"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEADLY_POISON"
              },
              {
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "id": "CARD.DEFLECT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFLECT"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.DEFLECT"
              },
              {
                "id": "CARD.TACTICIAN"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TACTICIAN"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.TACTICIAN"
              },
              {
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "id": "CARD.PREPARED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PREPARED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PREPARED"
              },
              {
                "id": "CARD.ANTICIPATE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ANTICIPATE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.ANTICIPATE"
              },
              {
                "id": "CARD.CLOAK_AND_DAGGER"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.CLOAK_AND_DAGGER"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.CLOAK_AND_DAGGER"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DRAFT.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.SLICE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ACCURACY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.LEG_SWEEP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DODGE_AND_ROLL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DASH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 1,
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SLICE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SLICE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SLICE"
              },
              {
                "id": "CARD.UNTOUCHABLE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.UNTOUCHABLE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.UNTOUCHABLE"
              },
              {
                "id": "CARD.FLICK_FLACK"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FLICK_FLACK"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FLICK_FLACK"
              },
              {
                "id": "CARD.SUCKER_PUNCH"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SUCKER_PUNCH"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.SUCKER_PUNCH"
              },
              {
                "id": "CARD.PREPARED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PREPARED"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.PREPARED"
              },
              {
                "id": "CARD.BACKFLIP"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.BACKFLIP"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.BACKFLIP"
              },
              {
                "id": "CARD.POISONED_STAB"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.POISONED_STAB"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.POISONED_STAB"
              },
              {
                "id": "CARD.LEG_SWEEP"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.LEG_SWEEP"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.LEG_SWEEP"
              },
              {
                "id": "CARD.FLICK_FLACK"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FLICK_FLACK"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FLICK_FLACK"
              },
              {
                "id": "CARD.LEADING_STRIKE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.LEADING_STRIKE"
              },
              {
                "floor_added_to_deck": 1,
                "id": "CARD.LEADING_STRIKE"
              }
            ],
            "current_gold": 99,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "DRAFT.title",
                  "table": "modifiers"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 56,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              }
            ],
            "current_gold": 111,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NOXIOUS_FUMES"
              },
              {
                "floor_added_to_deck": 2,
                "id": "CARD.NOXIOUS_FUMES"
              },
              {
                "floor_added_to_deck": 2,
                "id": "CARD.NOXIOUS_FUMES"
              }
            ],
            "current_gold": 108,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ACROBATICS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLECHETTES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLADE_DANCE"
              },
              {
                "floor_added_to_deck": 3,
                "id": "CARD.BLADE_DANCE"
              },
              {
                "floor_added_to_deck": 3,
                "id": "CARD.BLADE_DANCE"
              }
            ],
            "current_gold": 124,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 3,
                "id": "CARD.PIERCING_WAIL"
              },
              {
                "floor_added_to_deck": 3,
                "id": "CARD.PIERCING_WAIL"
              }
            ],
            "current_gold": 115,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.EXPOSE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.EXPOSE"
              },
              {
                "floor_added_to_deck": 4,
                "id": "CARD.EXPOSE"
              },
              {
                "floor_added_to_deck": 4,
                "id": "CARD.EXPOSE"
              }
            ],
            "current_gold": 134,
            "current_hp": 54,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CLOAK_AND_DAGGER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOUNCING_FLASK"
              },
              {
                "floor_added_to_deck": 4,
                "id": "CARD.BOUNCING_FLASK"
              },
              {
                "floor_added_to_deck": 4,
                "id": "CARD.BOUNCING_FLASK"
              }
            ],
            "current_gold": 129,
            "current_hp": 50,
            "damage_taken": 6,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 149,
            "current_hp": 52,
            "damage_taken": 2,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DEADLY_POISON"
              },
              {
                "floor_added_to_deck": 5,
                "id": "CARD.DEADLY_POISON"
              },
              {
                "floor_added_to_deck": 5,
                "id": "CARD.DEADLY_POISON"
              }
            ],
            "current_gold": 144,
            "current_hp": 50,
            "damage_taken": 0,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_NORMAL",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 149,
            "current_hp": 58,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WATERLOGGED_SCRIPTORIUM.pages.INITIAL.options.BLOODY_INK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 70,
            "max_hp_gained": 6,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "current_gold": 144,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "WATERLOGGED_SCRIPTORIUM.pages.INITIAL.options.BLOODY_INK.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 70,
            "max_hp_gained": 6,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.WATERLOGGED_SCRIPTORIUM",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.MIRAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MIRAGE"
              },
              {
                "floor_added_to_deck": 7,
                "id": "CARD.MIRAGE"
              },
              {
                "floor_added_to_deck": 7,
                "id": "CARD.MIRAGE"
              }
            ],
            "current_gold": 161,
            "current_hp": 55,
            "damage_taken": 3,
            "event_choices": [
              {
                "title": {
                  "key": "PUNCH_OFF.pages.INITIAL.options.I_CAN_TAKE_THEM.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "PUNCH_OFF.pages.I_CAN_TAKE_THEM.options.FIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPEEDSTER"
              },
              {
                "floor_added_to_deck": 7,
                "id": "CARD.SPEEDSTER"
              },
              {
                "floor_added_to_deck": 7,
                "id": "CARD.SPEEDSTER"
              }
            ],
            "current_gold": 153,
            "current_hp": 38,
            "damage_taken": 18,
            "event_choices": [
              {
                "title": {
                  "key": "PUNCH_OFF.pages.INITIAL.options.I_CAN_TAKE_THEM.title",
                  "table": "events"
                }
              },
              {
                "title": {
                  "key": "PUNCH_OFF.pages.I_CAN_TAKE_THEM.options.FIGHT.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 69,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BOWLER_HAT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PUNCH_OFF",
            "room_type": "event",
            "turns_taken": 0
          },
          {
            "model_id": "ENCOUNTER.PUNCH_OFF_EVENT_ENCOUNTER",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.PUNCH_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.ACCURACY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SKEWER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ACCURACY"
              },
              {
                "floor_added_to_deck": 8,
                "id": "CARD.ACCURACY"
              },
              {
                "floor_added_to_deck": 8,
                "id": "CARD.ACCURACY"
              }
            ],
            "current_gold": 192,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.VENERABLE_TEA_SET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.KNIFE_TRAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.DAGGER_THROW"
              },
              {
                "floor_added_to_deck": 8,
                "id": "CARD.DAGGER_THROW"
              },
              {
                "floor_added_to_deck": 8,
                "id": "CARD.DAGGER_THROW"
              }
            ],
            "current_gold": 186,
            "current_hp": 25,
            "damage_taken": 13,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 68,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.SHACKLING_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.FLEX_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MERCURY_HOURGLASS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 227,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "relic_choices": [
              {
                "choice": "RELIC.WAR_PAINT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.TACTICIAN",
              "CARD.EXPOSE"
            ]
          },
          {
            "current_gold": 229,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 43,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 67,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "relic_choices": [
              {
                "choice": "RELIC.RIPPLE_BASIN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.BULLET_TIME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BULLET_TIME"
              },
              {
                "floor_added_to_deck": 10,
                "id": "CARD.BULLET_TIME"
              },
              {
                "floor_added_to_deck": 10,
                "id": "CARD.BULLET_TIME"
              }
            ],
            "current_gold": 237,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.ATTACK_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 10,
                  "id": "CARD.POISONED_STAB"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.POISONED_STAB"
              },
              {
                "floor_added_to_deck": 10,
                "id": "CARD.POISONED_STAB"
              },
              {
                "floor_added_to_deck": 10,
                "id": "CARD.POISONED_STAB"
              }
            ],
            "current_gold": 239,
            "current_hp": 25,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 66,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TWO_TAILED_RATS_NORMAL",
            "monster_ids": [
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 237,
            "current_hp": 65,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 239,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 65,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UNTOUCHABLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.INFINITE_BLADES"
              },
              {
                "floor_added_to_deck": 12,
                "id": "CARD.INFINITE_BLADES"
              },
              {
                "floor_added_to_deck": 12,
                "id": "CARD.INFINITE_BLADES"
              }
            ],
            "current_gold": 247,
            "current_hp": 62,
            "damage_taken": 3,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 12,
                  "id": "CARD.PREPARED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PIERCING_WAIL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PREPARED"
              },
              {
                "floor_added_to_deck": 12,
                "id": "CARD.PREPARED"
              },
              {
                "floor_added_to_deck": 12,
                "id": "CARD.PREPARED"
              }
            ],
            "current_gold": 250,
            "current_hp": 42,
            "damage_taken": 2,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 64,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEWER_CLAM_NORMAL",
            "monster_ids": [
              "MONSTER.SEWER_CLAM"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SLICE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "current_gold": 261,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SNAKEBITE"
              },
              {
                "floor_added_to_deck": 13,
                "id": "CARD.SNAKEBITE"
              },
              {
                "floor_added_to_deck": 13,
                "id": "CARD.SNAKEBITE"
              }
            ],
            "current_gold": 273,
            "current_hp": 42,
            "damage_taken": 0,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": -5,
            "hp_healed": 0,
            "max_hp": 63,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC",
              "MONSTER.SNEAKY_GREMLIN",
              "MONSTER.FAT_GREMLIN"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.CALCULATED_GAMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CALCULATED_GAMBLE"
              },
              {
                "floor_added_to_deck": 14,
                "id": "CARD.CALCULATED_GAMBLE"
              },
              {
                "floor_added_to_deck": 14,
                "id": "CARD.CALCULATED_GAMBLE"
              }
            ],
            "current_gold": 292,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEADLY_POISON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ANTICIPATE"
              },
              {
                "floor_added_to_deck": 14,
                "id": "CARD.ANTICIPATE"
              },
              {
                "floor_added_to_deck": 14,
                "id": "CARD.ANTICIPATE"
              }
            ],
            "current_gold": 311,
            "current_hp": 25,
            "damage_taken": 17,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 62,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GAME_PIECE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 292,
            "current_hp": 61,
            "damage_taken": 1,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 61,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ACCURACY"
            ]
          },
          {
            "current_gold": 311,
            "current_hp": 43,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 61,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.FAN_OF_KNIVES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRACKING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FAN_OF_KNIVES"
              },
              {
                "floor_added_to_deck": 16,
                "id": "CARD.FAN_OF_KNIVES"
              },
              {
                "floor_added_to_deck": 16,
                "id": "CARD.FAN_OF_KNIVES"
              }
            ],
            "current_gold": 367,
            "current_hp": 42,
            "damage_taken": 19,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 60,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 16,
                  "id": "CARD.ADRENALINE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THE_HUNT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CORROSIVE_WAVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ADRENALINE"
              },
              {
                "floor_added_to_deck": 16,
                "id": "CARD.ADRENALINE"
              },
              {
                "floor_added_to_deck": 16,
                "id": "CARD.ADRENALINE"
              }
            ],
            "current_gold": 404,
            "current_hp": 22,
            "damage_taken": 21,
            "gold_gained": 93,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 60,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.WEAK_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LAGAVULIN_MATRIARCH_BOSS",
            "monster_ids": [
              "MONSTER.LAGAVULIN_MATRIARCH"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_FLESH",
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_WING",
                "title": {
                  "key": "PAELS_WING.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_BLOOD",
                "title": {
                  "key": "PAELS_BLOOD.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 367,
            "current_hp": 56,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 14,
            "max_hp": 59,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_FLESH",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_TEARS",
                "title": {
                  "key": "PAELS_TEARS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_GROWTH",
                "title": {
                  "key": "PAELS_GROWTH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_EYE",
                "title": {
                  "key": "PAELS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "current_gold": 404,
            "current_hp": 52,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_EYE.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 30,
            "max_hp": 59,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_EYE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PINPOINT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FOOTWORK"
              },
              {
                "floor_added_to_deck": 18,
                "id": "CARD.FOOTWORK"
              },
              {
                "floor_added_to_deck": 18,
                "id": "CARD.FOOTWORK"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.FOOTWORK"
              }
            ],
            "current_gold": 378,
            "current_hp": 54,
            "damage_taken": 2,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 58,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 18,
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "floor_added_to_deck": 7,
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BACKSTAB"
              },
              {
                "floor_added_to_deck": 18,
                "id": "CARD.BACKSTAB"
              },
              {
                "floor_added_to_deck": 18,
                "id": "CARD.BACKSTAB"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 7,
                "id": "CARD.SPEEDSTER"
              }
            ],
            "current_gold": 422,
            "current_hp": 49,
            "damage_taken": 3,
            "gold_gained": 18,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 58,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.BLADE_DANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLADE_DANCE"
              },
              {
                "floor_added_to_deck": 19,
                "id": "CARD.BLADE_DANCE"
              },
              {
                "floor_added_to_deck": 19,
                "id": "CARD.BLADE_DANCE"
              }
            ],
            "current_gold": 385,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.SUCKER_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SPEEDSTER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SUCKER_PUNCH"
              },
              {
                "floor_added_to_deck": 19,
                "id": "CARD.SUCKER_PUNCH"
              },
              {
                "floor_added_to_deck": 19,
                "id": "CARD.SUCKER_PUNCH"
              }
            ],
            "current_gold": 439,
            "current_hp": 44,
            "damage_taken": 5,
            "gold_gained": 17,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 57,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_NECTAR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREDATOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RICOCHET"
                },
                "was_picked": false
              }
            ],
            "current_gold": 396,
            "current_hp": 54,
            "damage_taken": 0,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 56,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.SWIFT_POTION",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 20,
                  "id": "CARD.SKEWER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PRECISE_CUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SKEWER"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.SKEWER"
              },
              {
                "floor_added_to_deck": 20,
                "id": "CARD.SKEWER"
              }
            ],
            "current_gold": 447,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 56,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.MIRAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BUBBLE_BUBBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.POUNCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MIRAGE"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.MIRAGE"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.MIRAGE"
              }
            ],
            "current_gold": 408,
            "current_hp": 49,
            "damage_taken": 5,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 55,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.BOUNCING_FLASK"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.EXPOSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BOUNCING_FLASK"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.BOUNCING_FLASK"
              },
              {
                "floor_added_to_deck": 21,
                "id": "CARD.BOUNCING_FLASK"
              }
            ],
            "current_gold": 459,
            "current_hp": 37,
            "damage_taken": 7,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 55,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER",
              "MONSTER.TOUGH_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_SPRAY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BACKFLIP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SEEKER_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BEAT_DOWN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.NOXIOUS_FUMES"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.NOXIOUS_FUMES"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.NOXIOUS_FUMES"
              }
            ],
            "current_gold": 333,
            "current_hp": 49,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 54,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              },
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.WHETSTONE",
                "was_picked": false
              },
              {
                "choice": "RELIC.STRIKE_DUMMY",
                "was_picked": false
              },
              {
                "choice": "RELIC.BELT_BUCKLE",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "floor_added_to_deck": 22,
                  "id": "CARD.MURDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FINISHER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MURDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOOTWORK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.AUTOMATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SECRET_TECHNIQUE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 22,
                "id": "CARD.DEFLECT"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.DEFLECT"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.DEFLECT"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.MURDER"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.MURDER"
              },
              {
                "floor_added_to_deck": 22,
                "id": "CARD.MURDER"
              }
            ],
            "current_gold": 75,
            "current_hp": 37,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 384,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 54,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.CLARITY",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MINIATURE_TENT",
                "was_picked": true
              },
              {
                "choice": "RELIC.ODDLY_SMOOTH_STONE",
                "was_picked": false
              },
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": false
              },
              {
                "choice": "RELIC.MINIATURE_TENT",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 333,
            "current_hp": 35,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 53,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 75,
            "current_hp": 23,
            "damage_taken": 14,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.SEARCH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 53,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "relic_choices": [
              {
                "choice": "RELIC.CHOSEN_CHEESE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 371,
            "current_hp": 35,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 52,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "relic_choices": [
              {
                "choice": "RELIC.LUCKY_FYSH",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 121,
            "current_hp": 23,
            "damage_taken": 0,
            "gold_gained": 46,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 52,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "relic_choices": [
              {
                "choice": "RELIC.ANCHOR",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 371,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 16,
            "max_hp": 51,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 121,
            "current_hp": 38,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 51,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "rest_site_choices": [
              "HEAL",
              "SMITH",
              "MEND"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.MURDER"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BACKSTAB"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              }
            ],
            "current_gold": 397,
            "current_hp": 28,
            "damage_taken": 24,
            "gold_gained": 26,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 1,
            "max_hp": 51,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "relic_choices": [
              {
                "choice": "RELIC.PEN_NIB",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 26,
                  "id": "CARD.ANTICIPATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ANTICIPATE"
              },
              {
                "floor_added_to_deck": 26,
                "id": "CARD.ANTICIPATE"
              },
              {
                "floor_added_to_deck": 26,
                "id": "CARD.ANTICIPATE"
              }
            ],
            "current_gold": 154,
            "current_hp": 30,
            "damage_taken": 18,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 51,
            "max_hp_gained": 1,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.STABLE_SERUM",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.REGEN_POTION",
              "POTION.SHACKLING_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.STONE_CALENDAR",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.REGAL_PILLOW"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.PRECISE_CUT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEADING_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PREPARED"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SNAKEBITE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.NOXIOUS_FUMES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DISCOVERY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ENTROPY"
                },
                "was_picked": false
              }
            ],
            "current_gold": 202,
            "current_hp": 28,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 195,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 50,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              },
              {
                "choice": "RELIC.LETTER_OPENER",
                "was_picked": false
              },
              {
                "choice": "RELIC.GHOST_SEED",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          },
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 27,
                  "id": "CARD.DEFLECT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FLICK_FLACK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DAGGER_THROW"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.EXPERTISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DEFLECT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFINITE_BLADES"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HUDDLE_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RALLY"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 27,
                "id": "CARD.DEFLECT"
              },
              {
                "floor_added_to_deck": 27,
                "id": "CARD.DEFLECT"
              },
              {
                "floor_added_to_deck": 27,
                "id": "CARD.DEFLECT"
              }
            ],
            "current_gold": 106,
            "current_hp": 30,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 48,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 50,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.SPEED_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.CANDELABRA",
                "was_picked": false
              },
              {
                "choice": "RELIC.PETRIFIED_TOAD",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_transformed": [
              {
                "final_card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.LEG_SWEEP"
                },
                "original_card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.CALCULATED_GAMBLE"
                }
              }
            ],
            "current_gold": 217,
            "current_hp": 28,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SYMBIOTE.pages.INITIAL.options.KILL_WITH_FIRE.title",
                  "table": "events"
                },
                "variables": {
                  "Enchantment": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Corrupted"
                  }
                }
              }
            ],
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 49,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "cards_enchanted": [
              {
                "card": {
                  "enchantment": {
                    "amount": 1,
                    "id": "ENCHANTMENT.CORRUPTED"
                  },
                  "floor_added_to_deck": 20,
                  "id": "CARD.SKEWER"
                },
                "enchantment": "ENCHANTMENT.CORRUPTED"
              }
            ],
            "current_gold": 106,
            "current_hp": 30,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SYMBIOTE.pages.INITIAL.options.APPROACH.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 49,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SYMBIOTE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.CALCULATED_GAMBLE"
              }
            ],
            "current_gold": 217,
            "current_hp": 28,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                },
                "variables": {
                  "RandomCard": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Calculated Gamble"
                  },
                  "HpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 3,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 48,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "stolen_loot": 0
          },
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 18,
                "id": "CARD.BACKSTAB"
              }
            ],
            "current_gold": 106,
            "current_hp": 30,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SLIPPERY_BRIDGE.pages.INITIAL.options.OVERCOME.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 48,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SLIPPERY_BRIDGE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 217,
            "current_hp": 47,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 47,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 106,
            "current_hp": 44,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 14,
            "max_hp": 47,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "rest_site_choices": [
              "HEAL",
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.DEFLECT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 217,
            "current_hp": 0,
            "damage_taken": 41,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 46,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198385749258,
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          },
          {
            "current_gold": 106,
            "current_hp": 0,
            "damage_taken": 32,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 46,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 76561198403716343,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 7
          }
        ]
      }
    ]
  ],
  "modifiers": [
    {
      "id": "MODIFIER.HOARDER"
    },
    {
      "id": "MODIFIER.DRAFT"
    },
    {
      "id": "MODIFIER.TERMINAL"
    }
  ],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "DAMAGE_LEADER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BACKSTAB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BACKSTAB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BACKSTAB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEADLY_POISON"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEADLY_POISON"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEADLY_POISON"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TACTICIAN"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.TACTICIAN"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.TACTICIAN"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.CLOAK_AND_DAGGER"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 4,
          "id": "CARD.EXPOSE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.EXPOSE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.EXPOSE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.MIRAGE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.MIRAGE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.MIRAGE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 8,
          "id": "CARD.ACCURACY"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.ACCURACY"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.ACCURACY"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.BULLET_TIME"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.BULLET_TIME"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.BULLET_TIME"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.INFINITE_BLADES"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.INFINITE_BLADES"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.INFINITE_BLADES"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.CALCULATED_GAMBLE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.FAN_OF_KNIVES"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.FAN_OF_KNIVES"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.FAN_OF_KNIVES"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.FOOTWORK"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.BLADE_DANCE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.MIRAGE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.MIRAGE"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.MIRAGE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.LEG_SWEEP"
        }
      ],
      "id": 76561198385749258,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.TOUCH_OF_INSANITY",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.FESTIVE_POPPER"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.VENERABLE_TEA_SET",
          "props": {
            "bools": [
              {
                "name": "GainEnergyInNextCombat",
                "value": false
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.WAR_PAINT"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_FLESH"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.LUCKY_FYSH"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.PEN_NIB",
          "props": {
            "ints": [
              {
                "name": "AttacksPlayed",
                "value": 8
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 27,
          "id": "RELIC.REGAL_PILLOW"
        }
      ]
    },
    {
      "badges": [
        {
          "id": "DEBUFFER",
          "rarity": "bronze"
        },
        {
          "id": "ELITE",
          "rarity": "bronze"
        },
        {
          "id": "HEALER",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.SILENT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SLICE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SLICE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SLICE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNTOUCHABLE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNTOUCHABLE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.UNTOUCHABLE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SUCKER_PUNCH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SUCKER_PUNCH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.SUCKER_PUNCH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BACKFLIP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.POISONED_STAB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.POISONED_STAB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.POISONED_STAB"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEG_SWEEP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEG_SWEEP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEG_SWEEP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FLICK_FLACK"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.LEADING_STRIKE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.NOXIOUS_FUMES"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.PIERCING_WAIL"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.BOUNCING_FLASK"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.BOUNCING_FLASK"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.BOUNCING_FLASK"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.DEADLY_POISON"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.DEADLY_POISON"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.DEADLY_POISON"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.SPEEDSTER"
        },
        {
          "floor_added_to_deck": 7,
          "id": "CARD.SPEEDSTER"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.DAGGER_THROW"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.POISONED_STAB"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.POISONED_STAB"
        },
        {
          "floor_added_to_deck": 10,
          "id": "CARD.POISONED_STAB"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 12,
          "id": "CARD.PREPARED"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.SNAKEBITE"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.SNAKEBITE"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.SNAKEBITE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 16,
          "id": "CARD.ADRENALINE"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.BACKSTAB"
        },
        {
          "floor_added_to_deck": 18,
          "id": "CARD.BACKSTAB"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.SUCKER_PUNCH"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.SUCKER_PUNCH"
        },
        {
          "floor_added_to_deck": 19,
          "id": "CARD.SUCKER_PUNCH"
        },
        {
          "enchantment": {
            "amount": 1,
            "id": "ENCHANTMENT.CORRUPTED"
          },
          "floor_added_to_deck": 20,
          "id": "CARD.SKEWER"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.SKEWER"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.SKEWER"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.BOUNCING_FLASK"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.BOUNCING_FLASK"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.BOUNCING_FLASK"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.MURDER"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.MURDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.MURDER"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 26,
          "id": "CARD.ANTICIPATE"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.DEFLECT"
        },
        {
          "floor_added_to_deck": 27,
          "id": "CARD.DEFLECT"
        }
      ],
      "id": 76561198403716343,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.STABLE_SERUM",
          "slot_index": 0
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.RING_OF_THE_SNAKE"
        },
        {
          "floor_added_to_deck": 7,
          "id": "RELIC.BOWLER_HAT"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.MERCURY_HOURGLASS"
        },
        {
          "floor_added_to_deck": 9,
          "id": "RELIC.RIPPLE_BASIN"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.GAME_PIECE"
        },
        {
          "floor_added_to_deck": 17,
          "id": "RELIC.PAELS_EYE"
        },
        {
          "floor_added_to_deck": 22,
          "id": "RELIC.MINIATURE_TENT"
        },
        {
          "floor_added_to_deck": 23,
          "id": "RELIC.CHOSEN_CHEESE"
        },
        {
          "floor_added_to_deck": 24,
          "id": "RELIC.ANCHOR"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.STONE_CALENDAR"
        }
      ]
    }
  ],
  "run_time": 3708,
  "schema_version": 9,
  "seed": "22_08_2026_2P",
  "start_time": 1787375441,
  "was_abandoned": false,
  "win": false
}